### ISSUE TITLE
Is this C3 or what?

### ISSUE THREAD

**Issue by KristerV** [drarmstr/chartcollection#3]
On further reading it's confusing if this is C3 extra documentation (like it first seemed) or C3 extension or a completely new tool using only D3?
I mean I can dig into the code but would be nice to have a line about this in the readme.

And by C3 I mean c3js.org

**Comment by KristerV** [comment]
okay now I found the longer explanation of https://drarmstr.github.io/chartcollection/. So this is not compatible with c3js.org at all?

**Comment by drarmstr** [comment]
Correct, chartcollection is unaffiliated with c3js.org.
